# Generated by Django 4.2.3 on 2023-08-19 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import referrals.managers
import referrals.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(error_messages={'unique': 'Телефонный номер занят'}, max_length=12, unique=True, validators=[referrals.validators.PhoneNumberValidator], verbose_name='номер телефона')),
                ('invitation_code', models.CharField(max_length=6, null=True, verbose_name='код приглашения')),
                ('referrer_code', models.CharField(max_length=6, unique=True, verbose_name='код приглашающего')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', referrals.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4, unique=True, verbose_name='значение кода')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'код подтверждения',
                'verbose_name_plural': 'коды подтверждения',
            },
        ),
        migrations.CreateModel(
            name='Referring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL, verbose_name='приглашенный пользователь')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL, verbose_name='пригласивший пользователь')),
            ],
            options={
                'verbose_name': 'реферальная связь',
                'verbose_name_plural': 'реферальные связи',
            },
        ),
    ]
